> generated by whalee-helper

# ${serviceName} 初始化步骤

* 主目录: ${servicePath}
* proto 目录 : ${protoPackage}

1. 编译 ${protoPackage}/${shortName}.proto
2. go mod tiy
3. go run main.go

# jenkins 构建脚本

```bash
# working dir: git repository root

export GOROOT=/root/sdk/infra/go
export GOPATH=/var/lib/jenkins/go
export PATH=$GOROOT/bin:$GOPATH/bin:$PATH
export GOPROXY=https://goproxy.cn
export GO111MODULE=on

export JENKINS_ENV=bazel

cd ${servicePath}
chmod + x build.sh && . ./build.sh

```